on:
  push:
    branches: ["dev"]
env:
  IMAGE_VERSION: 1.1
name: Publishing app
jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Running App on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            docker stop sales_app 2> /dev/null || true
            docker rm sales_app 2> /dev/null || true
            docker run -d -p 9000:8888 --name sales_app krystian8207/sales_app:release-1.1
